mac:
	g++ -g -I /usr/local/include -L /usr/local/lib -o game -std=c++17 -lSDL2main -lSDL2 -lSDL2_image game.cc 
wind:
	g++ -g -I src/include -L src/lib -o game game.cc -std=c++17 -lmingw32 -lSDL2main -lSDL2 -lSDL2_image